#!/bin/bash

exec docker run \
    --rm \
    --tty \
    --interactive \
    --device=/dev/net/tun \
    --name=openvpn-client \
    --cap-add=NET_ADMIN \
    --publish 0.0.0.0:8118:8118 \
    --volume "$(realpath "$1"):/etc/openvpn/:ro" \
    --sysctl net.ipv6.conf.all.disable_ipv6=0 \
    docker-openvpn-client-socks:latest
